name: CI

on:
  push:
    branches: [ master ]

jobs:
  compile:
    name: Compile resume pdf
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: texlive/texlive
          options: -v ${{ github.workspace }}:/usr/src/app
          run: |
            cd /usr/src/app
            pdflatex -jobname=Akshay_Shegaonkar_SWE resume.tex
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply pdflatex changes
